# Author : Jakub Bartodziej <kubabartodziej@gmail.com>
# The theme uses the gruvbox dark palette with standard contrast: github.com/morhetz/gruvbox

"attribute" = "fg2"
"comment" = "gray1"
"constructor" = "fg2"
"diagnostic" = { modifiers = ["underlined"] }
"error" = "red0"
"escape" = { fg = "fg2", modifiers = ["bold"] }
"function" = "yellow0"
"function.macro" = "purple0"
"hint" = "gray0"
"info" = "blue0"
"keyword" = "red1"
"label" = "aqua1"
"module" = "red0"
"namespace" = "orange0"
"number" = "purple1"
"operator" = "blue0"
"property" = "fg2"
"punctuation" = "fg4"
"punctuation.delimiter" = "fg4"
"special" = "purple0"
"string" = "green1"
"type" = "yellow0"
"type.builtin" = "yellow1"
"ui.background" = { bg = "bg0" }
# "ui.cursor.insert" = { bg = "purple1" } # doesn't seem to work
"ui.cursor.primary" = { bg = "bg4" }
"ui.cursor.match" = { bg = "bg3" }
"ui.help" = { bg = "bg2", fg = "fg3" } # command help box
"ui.linenr" = { fg = "bg2" } # line number on the right
"ui.linenr.selected" = { fg = "bg4", modifiers = ["bold"] } # line number with a selection in it
"ui.menu.selected" = { fg = "fg2", bg = "bg2" } # selections in command menu (after pressing ":")
"ui.popup" = { fg = "fg2", bg = "bg1" } # the autocomplete menu and the documentation popup
"ui.selection" = { bg = "bg1" } # selections inside the editor
"ui.statusline" = { fg = "fg2", bg = "bg1" } # status line and command menu background
"ui.statusline.inactive" = { fg = "fg3", bg = "bg2" } # status line of inactive windows
"ui.text" = { fg = "fg1", bg = "bg0" } # normal text
"ui.text.focus" = { fg = "fg2" } # the command menu, the text in the buffer and file menu
"ui.window" = "bg1" # window borders
"variable.builtin" = "fg3"
"variable.parameter" = "fg2"
"warning" = "yellow0"

[palette]
bg0 = "#282828" # main background
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"

fg0 = "#fbf1c7"
fg1 = "#ebdbb2" # main foreground
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984" # gray0

gray0 = "#a89984"
gray1 = "#928374"

red0 = "#cc241d" # neutral
red1 = "#fb4934" # bright
green0 = "#98971a"
green1 = "#b8bb26"
yellow0 = "#d79921"
yellow1 = "#fabd2f"
blue0 = "#458588"
blue1 = "#83a598"
purple0 = "#b16286"
purple1 = "#d3869b"
aqua0 = "#689d6a"
aqua1 = "#8ec07c"
orange0 = "#d65d0e"
orange1 = "#fe8019"
